SDS/app/base/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

SDS/app/base/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired


## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

SDS/app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

SDS/app/base/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'accounts/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'accounts/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        # Check usename exists
        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Username already registered',
                                    success=False,
                                    form=create_account_form)

        # Check email exists
        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Email already registered', 
                                    success=False,
                                    form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'accounts/register.html', 
                                msg='User created please <a href="/login">login</a>', 
                                success=True,
                                form=create_account_form)

    else:
        return render_template( 'accounts/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('page-403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('page-403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('page-404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('page-500.html'), 500

SDS/app/base/templates/accounts/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-5">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">
            Login
          </h4>
        </div>
        <div class="card-body">

          <h6 class="card-category">
            {% if msg %}
              {{ msg | safe }}
            {% else %}
                Default Credentials: test / pass
            {% endif %} 
          </h6>
          
          <br />

          <form role="form" method="post" action="">

            {{ form.hidden_tag() }}                    

            <div class="input-group mb-3">
                {{ form.username(placeholder="Username", class="form-control") }}
            </div>
            
            <div class="input-group mb-4">
                {{ form.password(placeholder="Password", class="form-control", type="password") }}
            </div>
            
            <div class="form-group text-left">
              <div class="form-check">
                <label class="form-check-label">
                    <input class="form-check-input" type="checkbox" checked="">
                    Save Details
                    <span class="form-check-sign">
                        <span class="check"></span>
                    </span>
                </label>
            </div>

            <button type="submit" name="login" class="btn btn-primary shadow-2 mb-4">Login</button>

          </form>

          <p class="mb-0 text-muted">Don’t have an account? <a href="{{ url_for('base_blueprint.register') }}" >Signup</a></p>
          <br />

        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

SDS/app/base/templates/accounts/register.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-5">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">
            Create Account
          </h4>
        </div>
        <div class="card-body">

          <h6 class="card-category">
            {% if msg %}
                {{ msg | safe }}
            {% else %}
                Add your credentials
            {% endif %} 
          </h6>
          
          <br />
          <br />

          <!-- Hide the form on success -->
          {% if not success %}
              <form role="form" method="post" action="">

                  {{ form.hidden_tag() }}                    

                  <div class="input-group mb-3">
                      {{ form.username(placeholder="Username", class="form-control") }}
                  </div>
                  
                  <div class="input-group mb-3">
                      {{ form.email(placeholder="Email", class="input form-control", type="email") }}
                  </div>

                  <div class="input-group mb-4">
                      {{ form.password(placeholder="Password", class="form-control", type="password") }}
                  </div>
                  
                  <div class="form-group text-left">
                    <div class="form-check">
                      <label class="form-check-label">
                          <input class="form-check-input" type="checkbox" checked="">
                          Agree with <a href="#">terms</a>
                          <span class="form-check-sign">
                              <span class="check"></span>
                          </span>
                      </label>
                  </div>

                  <button type="submit" name="register" class="btn btn-primary shadow-2 mb-4">Register</button>

              </form>
              
              <p class="mb-0 text-muted">Already have an account? <a href="{{ url_for('base_blueprint.login') }}" >Login</a></p>
              <br />
          {% endif %}

        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

SDS/app/base/templates/includes/Test.html
<!DOCTYPE html>
<html>
<head>
    <title> test </title>
    <style>
        .notification {
  background-color: #555;
  color: white;
  text-decoration: none;
  padding: 15px 26px;
  position: relative;
  display: inline-block;
  border-radius: 2px;
}

.notification:hover {
  background: red;
}

.notification .badge {
  position: absolute;
  top: -10px;
  right: -10px;
  padding: 5px 10px;
  border-radius: 50%;
  background: red;
  color: white;
}

    </style>
</head>
<body>

    <a href="#" class="notification">
        <span>Inbox</span>
        <span class="badge">3</span>
      </a>
      
</body>
</html>

SDS/app/base/templates/includes/data.html
{% block title %} Dashboard {% endblock %} 

SDS/app/base/templates/includes/fixed-plugin.html
  <div class="fixed-plugin">
    <div class="dropdown show-dropdown">
      <a href="#" data-toggle="dropdown">
        <i class="fa fa-cog fa-2x"> </i>
      </a>
      <ul class="dropdown-menu">
        <li class="header-title"> Sidebar Filters</li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger active-color">
            <div class="badge-colors ml-auto mr-auto">
              <span class="badge filter badge-purple" data-color="purple"></span>
              <span class="badge filter badge-azure" data-color="azure"></span>
              <span class="badge filter badge-green" data-color="green"></span>
              <span class="badge filter badge-warning" data-color="orange"></span>
              <span class="badge filter badge-danger" data-color="danger"></span>
              <span class="badge filter badge-rose active" data-color="rose"></span>
            </div>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="header-title">Images</li>
        <li class="active">
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/static/assets/img/sidebar-1.jpg" alt="">
          </a>
        </li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/static/assets/img/sidebar-2.jpg" alt="">
          </a>
        </li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/static/assets/img/sidebar-3.jpg" alt="">
          </a>
        </li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/static/assets/img/sidebar-4.jpg" alt="">
          </a>
        </li>
        <li class="button-container">
          <a target="_blank" rel="noopener noreferrer"
             href="https://demos.creative-tim.com/material-dashboard-flask/docs/1.0/getting-started/getting-started-flask.html" 
             class="btn btn-default btn-block">
             Documentation 
          </a>
        </li>
        <li class="button-container">
          <a target="_blank" rel="noopener noreferrer" 
             href="https://www.creative-tim.com/product/material-dashboard-flask" class="btn btn-primary btn-block">
             See Product
          </a>
        </li>
      </ul>
    </div>
  </div>

SDS/app/base/templates/includes/footer.html
    <footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>

              <li>
                <a target="_blank" rel="noopener noreferrer" 
                   href="https://www.creative-tim.com/product/material-dashboard-flask">
                   Material Dashboard Flask
                </a>
              </li>

            </ul>
          </nav>
          <div class="copyright float-right">
            &copy; <a target="_blank" rel="noopener noreferrer" 
                      href="https://www.creative-tim.com/">Creative Tim</a> 
                      - coded by <a target="_blank" rel="noopener noreferrer" href="https://appseed.us">AppSeed</a>
          </div>
        </div>
    </footer>

SDS/app/base/templates/includes/navigation-rtl.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#pablo">داشبورد</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    آمارها
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">notifications</i>
                  <span class="notification">5</span>
                  <p class="d-lg-none d-md-block">
                    اعلان‌ها
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">محمدرضا به ایمیل شما پاسخ داد</a>
                  <a class="dropdown-item" href="#">شما ۵ وظیفه جدید دارید</a>
                  <a class="dropdown-item" href="#">از حالا شما با علیرضا دوست هستید</a>
                  <a class="dropdown-item" href="#">اعلان دیگر</a>
                  <a class="dropdown-item" href="#">اعلان دیگر</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                  <a class="dropdown-item" href="/page-user.html">Profile</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{{ url_for('base_blueprint.logout') }}" >Log out</a>
                </div>
              </li>
            </ul>
          </div>

        </div>
      </nav>

SDS/app/base/templates/includes/navigation-script.html
<script>
    function addNote(Notif){
    var myArray = JSON.parse(localStorage.getItem("notification"));
    if (myArray && Array.isArray((myArray))) {

           
        myArray.push(Notif);
        localStorage.setItem('notification', JSON.stringify(myArray))
        console.log(localStorage.getItem('notification'));

    }
    else{
        localStorage.setItem("notification", "[]");

    }
    show();
}
    
    function removeNote(){
    var myArray = JSON.parse(localStorage.getItem("notification"));
    if (myArray && Array.isArray((myArray))) {
        
        myArray.shift();
        localStorage.setItem("notification", JSON.stringify(myArray));
        console.log(localStorage.getItem('notification'));

    }
    else{
        localStorage.setItem("notification", "[]");
    }
    show();
    }
    function show(){
        var y = document.getElementById("NumberOfNote");
        var x = document.getElementById("badge");
        var storedNames = JSON.parse(localStorage.getItem("notification"));
        if (storedNames.length == 0){
            x.innerHTML = "";
            y.innerHTML = "You have no Notifications";
        }
        else{
            x.innerHTML = storedNames.length;
            y.innerHTML = "You have "+storedNames.length+" notifications";
        }
    }
    function setToZero(){
        localStorage.setItem("notification", "[]");
    }  
    show();
  </script>
  <script>
      
  </script>

SDS/app/base/templates/includes/navigation.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#pablo">Social Distancing System</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>

          {% if current_user.is_authenticated %}
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link"  href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" onclick="setToZero()">
                  <i class="material-icons">notifications</i>
                  <span class="badge" id = "badge"></span>
                  <p class="d-lg-none d-md-block">
                    Notifications
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="/ui-tables.html" id = "NumberOfNote"></a>
                  <a class="dropdown-item" href="#">Another Notification</a>
                  <a class="dropdown-item" href="#">Another One</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                  <a class="dropdown-item" href="/page-user.html">Profile</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{{ url_for('base_blueprint.logout') }}" >Log out</a>
                </div>
              </li>
            </ul>
          </div>
          {% endif %}
          
        </div>
      </nav>

SDS/app/base/templates/includes/scripts.html
  <!--   Core JS Files   -->
  <script src="/static/assets/js/core/jquery.min.js"></script>
  <script src="/static/assets/js/core/popper.min.js"></script>
  <script src="/static/assets/js/core/bootstrap-material-design.min.js"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!-- Plugin for the momentJs  -->
  <script src="/static/assets/js/plugins/moment.min.js"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="/static/assets/js/plugins/sweetalert2.js"></script>
  <!-- Forms Validations Plugin -->
  <script src="/static/assets/js/plugins/jquery.validate.min.js"></script>
  <!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
  <script src="/static/assets/js/plugins/jquery.bootstrap-wizard.js"></script>
  <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="/static/assets/js/plugins/bootstrap-selectpicker.js"></script>
  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
  <script src="/static/assets/js/plugins/bootstrap-datetimepicker.min.js"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
  <script src="/static/assets/js/plugins/jquery.dataTables.min.js"></script>
  <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <script src="/static/assets/js/plugins/bootstrap-tagsinput.js"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="/static/assets/js/plugins/jasny-bootstrap.min.js"></script>
  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
  <script src="/static/assets/js/plugins/fullcalendar.min.js"></script>
  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
  <script src="/static/assets/js/plugins/jquery-jvectormap.js"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="/static/assets/js/plugins/nouislider.min.js"></script>
  <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
  <!-- Library for adding dinamically elements -->
  <script src="/static/assets/js/plugins/arrive.min.js"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chartist JS -->
  <script src="/static/assets/js/plugins/chartist.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="/static/assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Chart.js-->
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="/static/assets/js/material-dashboard.js?v=2.1.1" type="text/javascript"></script>
  <script>
    
//     $.notify({
//   icon:"report_problem",
// 	title: "Violation alert:",
// 	message: "A Violation has been detected click here to see the log"
// },{
//   type:"danger",
//   allow_dismiss: true,
// 	placement: {
// 		from: "top",
// 		align: "right"
// 	},
// 	delay: 5000,
// 	timer: 1000
// }
// );

</script>
  

SDS/app/base/templates/includes/sidebar-rtl.html
    <div class="sidebar" data-color="azure" data-background-color="white" data-image="/static/assets/img/sidebar-1.jpg">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
      <div class="logo">
        <a target="_blank" rel="noopener noreferrer" 
           href="https://github.com/app-generator/jinja-template-material-dashboard" class="simple-text logo-normal">
          تیم خلاق
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item ">
            <a class="nav-link" href="/">
              <i class="material-icons">dashboard</i>
              <p>داشبورد</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="/page-user.html">
              <i class="material-icons">person</i>
              <p>پروفایل کاربر</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="/ui-tables.html">
              <i class="material-icons">content_paste</i>
              <p>جدول</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="/ui-typography.html">
              <i class="material-icons">library_books</i>
              <p>تایپوگرافی</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="/ui-icons.html">
              <i class="material-icons">bubble_chart</i>
              <p>آیکن‌ها</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="/ui-maps.html">
              <i class="material-icons">location_ons</i>
              <p>نقشه</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="/ui-notifications.html">
              <i class="material-icons">notifications</i>
              <p>اعلان‌ها</p>
            </a>
          </li>
          <li class="nav-item active  ">
            <a class="nav-link" href="/page-rtl-support.html">
              <i class="material-icons">language</i>
              <p>پشتیبانی از راست به چپ</p>
            </a>
          </li>

          <li class="nav-item ">
            <a class="nav-link" href="{{ url_for('base_blueprint.logout') }}" >
              <i class="material-icons">directions_run</i>
              <p>Logout</p>
            </a>
          </li>

          <li class="nav-item active-pro ">
            <a target="_blank" rel="noopener noreferrer"  
               class="nav-link" href="https://www.creative-tim.com/templates/flask">
               <i class="material-icons">cloud_download</i>
               <p>More Starters</p>
            </a>
          </li>
        </ul>
      </div>
    </div>

SDS/app/base/templates/includes/sidebar.html
    <div class="sidebar" data-color="green" data-background-color="white" data-image="/static/assets/img/sidebar-1.jpg">
      <div class="logo">
        <a target="_blank" rel="noopener noreferrer" 
           href="https://github.com/app-generator/jinja-template-material-dashboard" class="simple-text logo-normal">
          SDS Dashboard
        </a>
      </div>
      <div class="sidebar-wrapper">
        
        <ul class="nav">

          {% if current_user.is_authenticated %}
          <li class="nav-item {% if 'index' in segment %} active {% endif %}">
            <a class="nav-link" href="/">
              <i class="material-icons">masks</i>
              <p>Camera 01 | Face Mask</p>
            </a>
          </li>
          <li class="nav-item {% if 'camera02' in segment %} active {% endif %}">
            <a class="nav-link" href="/camera02.html">
              <i class="material-icons">6_ft_apart</i>
              <p>Camera 02 | social distancing </p>
            </a>
          </li>
          <li class="nav-item {% if 'analytics' in segment %} active {% endif %}">
            <a class="nav-link" href="/analytics.html">
              <i class="material-icons">analytics</i>
              <p>Analytics</p>
            </a>
          </li>
          <li class="nav-item {% if 'ui-tables' in segment %} active {% endif %}">
            <a class="nav-link" href="/ui-tables.html">
              <i class="material-icons">report_problem</i>
              <p>Violations </p>
            </a>
          </li>
          <li class="nav-item {% if 'ui-icons' in segment %} active {% endif %}">
            <a class="nav-link" href="/ui-icons.html">
              <i class="material-icons">bubble_chart</i>
              <p>Icons</p>
            </a>
          </li>
          <li class="nav-item {% if 'ui-notifications' in segment %} active {% endif %}">
            <a class="nav-link" href="/ui-notifications.html">
              <i class="material-icons">notifications</i>
              <p>Notifications</p>
            </a>
          </li>
          

          <li class="nav-item ">
            <a class="nav-link" href="{{ url_for('base_blueprint.logout') }}" >
              <i class="material-icons">directions_run</i>
              <p>Logout</p>
            </a>
          </li>
          {% endif %}

        </ul>


      </div>

    </div>